[theme]
name = 'Sample'
comment = 'This is sample cursor theme'
website = 'https://www.example.com/'

[config]
bitmaps_dir = 'pngs'
out_dir = 'out'
platforms = ['x11', 'windows']
x11_sizes = [21, 24, 28, 32, 40, 48, 56, 64, 72, 80, 88, 96]
win_size = 32

[cursors]

[cursors.fallback_settings]
x11_sizes = [21, 24, 28, 32, 40, 48, 56, 64, 72, 80, 88, 96]
win_sizes = 32
x_hotspot = 100
y_hotspot = 100
x11_delay = 30
win_delay = 1

[cursors.pointer]
png = 'pointer.png'
x_hotspot = 53
y_hotspot = 36
win_name = 'Default'
x11_name = 'left_ptr'
x11_symlinks = ['c']

[cursors.wait]
png = 'wait-*.png'
win_name = 'Work'
x11_name = 'wait'
x11_symlinks = ['d', 'e', 'f']

[cursors.progress]
png = 'wait-*.png'
win_name = 'Progress'
x11_name = 'progress'
win_sizes = [20]
