name: CI

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE
    branches:
      - main
      - dev

  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: |
          sudo apt install libx11-dev libxcursor-dev libpng-dev
        continue-on-error: false

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        continue-on-error: false

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Make
        run: python setup.py install
        continue-on-error: false

      - name: Testing
        run: |
          pip install -U pytest pytest-cov
          python -m pytest -vv
          pytest --cov=./ --cov-report=xml
        continue-on-error: false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true

      - uses: actions/upload-artifact@master
        if: success()
        with:
          name: coverage
          path: coverage.xml

      - uses: actions/upload-artifact@master
        if: success()
        with:
          name: xcursorgen
          path: clickgen/xcursorgen.so

      - name: Building Package
        run: python setup.py sdist bdist_wheel
        continue-on-error: false

      - uses: actions/upload-artifact@master
        if: success()
        with:
          name: dist
          path: dist
