name: CI

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE

  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Caching pip packages
        uses: actions/cache@v2
        id: pip-cache # use this to check for `cache-hit` (`steps.pip-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install build dependencies using 'apt'
        run: sudo apt install libx11-dev libxcursor-dev libpng-dev
        continue-on-error: false

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install tox-gh-actions
        continue-on-error: false

      - name: Compiling Xcursorgen C library
        run: make xcursorgen.so
        continue-on-error: false

      - name: Test with tox
        run: tox
        continue-on-error: false

  build:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python "3.x"
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install build dependencies using 'apt'
        run: sudo apt install libx11-dev libxcursor-dev libpng-dev
        continue-on-error: false

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install setuptools wheel
          python -m pip install pytest pytest-cov
        continue-on-error: false

      - name: Compiling Xcursorgen C library
        run: make -C src/xcursorgen
        continue-on-error: false

      - name: Building clickgen
        run: python setup.py sdist bdist_wheel
        continue-on-error: false

      - uses: actions/upload-artifact@master
        if: success()
        with:
          name: dist
          path: dist

      - name: Generating 'coverage.xml'
        run: |
          python -m pip install -e .
          python -m py.test --cov-report=xml --cov=src/clickgen tests/
        continue-on-error: false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true

      - uses: actions/upload-artifact@master
        if: success()
        with:
          name: coverage
          path: coverage.xml
