name: CI

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE

  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
    branches:
      - main

jobs:
  Linting:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python "3.x"
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Caching pip packages
        uses: actions/cache@v2
        id: pip-cache # use this to check for `cache-hit` (`steps.pip-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install 'flake8'
        run: |
          python -m pip install --upgrade pip
          pip install flake8
        continue-on-error: false

      - name: Linting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  Linux-Testing:
    needs: Linting
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Caching pip packages
        uses: actions/cache@v2
        id: pip-cache # use this to check for `cache-hit` (`steps.pip-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install build dependencies using 'apt'
        run: sudo apt install libx11-dev libxcursor-dev libpng-dev
        continue-on-error: false

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip

          # clickgen dependencies
          python -m pip install pillow

          # for Testing
          python -m pip install pytest
        continue-on-error: false

      - name: Testing
        run: |
          python setup.py install
          python -m pytest -vv
        continue-on-error: false

  build:
    needs: [Linting, Linux-Testing]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python "3.x"
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install build dependencies using 'apt'
        run: sudo apt install libx11-dev libxcursor-dev libpng-dev
        continue-on-error: false

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip

          # clickgen dependencies
          python -m pip install pillow

          # build dependencies
          python -m pip install setuptools wheel

          # test dependencies
          python -m pip install pytest pytest-cov
        continue-on-error: false

      - name: Build Xcursorgen
        run: make compile_xcursorgen
        continue-on-error: false

      - name: Package build
        run: python setup.py sdist bdist_wheel
        continue-on-error: false

      - name: Generating 'coverage.xml'
        run: python -m py.test --cov-report=xml --cov=src/clickgen tests/
        continue-on-error: false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true

      - uses: actions/upload-artifact@master
        if: success()
        with:
          name: coverage
          path: coverage.xml

      - uses: actions/upload-artifact@master
        if: success()
        with:
          name: dist
          path: dist

      - uses: actions/upload-artifact@master
        if: success()
        with:
          name: xcursorgen
          path: src/clickgen/xcursorgen.so
