name: Publish PyPI Package & Docker

on:
  release:
    types: [released, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Caching pip packages
        uses: actions/cache@v2
        id: pip-cache # use this to check for `cache-hit` (`steps.pip-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install build dependencies using 'apt'
        run: sudo apt install libx11-dev libxcursor-dev libpng-dev
        continue-on-error: false

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install mypy flake8 pytest
          python -m pip install setuptools wheel twine
        continue-on-error: false

      - name: Linting
        run: |
          flake8 src
          flake8 tests

      - name: Checking static types
        run: mypy src

      - name: Generating clickgen `stubfile`
        run: make stubgen

      - name: Compiling Xcursorgen C library
        run: make xcursorgen.so
        continue-on-error: false

      - name: Building
        run: python setup.py sdist bdist_wheel
        continue-on-error: false

      - uses: actions/upload-artifact@master
        if: success()
        with:
          name: dist
          path: dist

      - name: Testing
        run: |
          python -m pip install -e .
          python -m pytest
        continue-on-error: false

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/clickgen
          cache_froms: python:3-alpine:latest
          tags: latest, 1.1
          tag_with_ref: true
        continue-on-error: false

      - name: Publishing to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine --version
          twine upload dist/*
